### ISSUE TITLE
Problem with filter

### ISSUE THREAD

**Issue by jw3126** [JuliaGizmos/Reactive.jl#100]
I copied the voting [example](http://julialang.org/Reactive.jl/#drop-repeats) from the documentation and it gives me an error:

```
using Reactive

votes = Signal(:NoVote)    # Let's :NoVote to denote the initial case

# Now we can split the vote stream into votes for alice and those for bob.

alice_votes = filter(v -> v == :Alice, votes)
bob_votes   = filter(v -> v == :Bob, votes)

# Now let's count the votes cast for alice and bob using foldp

function count(cnt, _)
  cnt+1
end

alice_count = foldp(count, 0, alice_votes)
bob_count = foldp(count, 0, bob_votes)
```

```
LoadError: type Filter has no field actions
while loading In[32], in expression starting on line 16

 in connect_foldp at /home/admin/.julia/v0.4/Reactive/src/operators.jl:112
 in foldp at /home/admin/.julia/v0.4/Reactive/src/operators.jl:105
```

**Comment by pyrex41** [comment]
I had the same issue when trying to follow the tutorial. Looking at the source code, it looks like the filter function now has a third argument for a default initial value. If you change alice_votes and bob_votes to:

`alice_votes = filter(v -> v == :Alice, :NoVote, votes)
bob_votes   = filter(v -> v == :Bob, :NoVote, votes)`

then the code should work as intended

**Comment by jw3126** [comment]
@pyrex41 Cool it works, thanks! You want to add a PR that fixes this point in the tutorial? Otherwise I would do it.
