### ISSUE TITLE
Signal not updating correctly?

### ISSUE THREAD

**Issue by jw3126** [JuliaGizmos/Reactive.jl#101]
Consider the following code

```
using Reactive

x1 = Signal(1)
x2 = Signal(10)
y1 = map(x1) do x println("computing y1"); x end
y2 = map(x2) do x println("computing y2"); x end
y12 = map(x1, x2) do args... println("computing y12"); +(args...) end
z = map(y1, y2, y12) do args... println("computing z"); +(args...) end
```

So z is the sum of ys and the ys depend in some way on the xs. Now lets update this:

```
push!(x1, 3)
sleep(1)
@show value(x1)
@show value(x2)
@show value(y1)
@show value(y2)
@show value(y12)
@show value(z);
```

which gives me

```
computing y1
computing z
computing y12
value(x1) = 3
value(x2) = 10
value(y1) = 3
value(y2) = 10
value(y12) = 13
value(z) = 24
```

All values look as I expected except for z. It was defined as sum of ys, so it should be 26. z should have been updated a second time after y12 changed right? Or do I misunderstand how Reactive.jl is supposed to work?

**Comment by JobJob** [comment]
Even simpler example, in IJulia notebook:

    using Reactive, Interact
    x = Signal(2)
    y = map(identity, x)
    x2 = map(x->2x, x)
    z = map((y,x)->y+x, y, x2)
    map(display, [x,y,x2,z]);

is all good, `z = y + x2 = x + 2x = 3x = 6`
`x`
`y`
`x2`
`z` are :

    2
    2
    4
    6

but then when you do

    push!(x,3)

it updates to:

    3
    3
    6
    7

basically, in the signal graph there are two paths to `z`, one via `y` and one via `x2`, the value of z only updates for the change in one of the paths, not both, so the old value of `x2`(4) is used in the result above (`z = y + x2 = 3 + 4 = 7`).

Is this not the recommended way to use the library to have a node that has 2 paths to it (`z` in this case) that will be activated by a change/push to a single node(`x` in this case).

n.b. this doesn't happen without the intermediate node `y` (i.e. if `z = x + x2`).

**Comment by JobJob** [comment]
Removing the `if prev_timestep != timestep` [here](https://github.com/JuliaLang/Reactive.jl/blob/master/src/operators.jl#L38) fixes it, not sure what the implications are of doing that...
