### ISSUE TITLE
Sync object properties

### ISSUE THREAD

**Issue by essenciary** [JuliaGizmos/Reactive.jl#114]
How can I be notified (have a callback function invoked) when the property of an object changes please? 

Ex: 
```julia
type Foo
  bar::String
  baz::Int
end

foo = Foo("hi", 3)

foo.baz = 4 # <= how can I be notified of this change? 
```

Thanks!

**Comment by shashi** [comment]
Usually you just have a signal of the object and have the whole object change.

There's no easy way to do what you want

**Comment by shashi** [comment]
I don't think Reactive.jl will ever implement this. Closing.
