### ISSUE TITLE
Tag v0.3.7? 

### ISSUE THREAD

**Issue by rdeits** [JuliaGizmos/Reactive.jl#122]
Hi! 

Would you be willing to tag v0.3.7 in METADATA? I'd love to be able to turn on precompilation for Interact.jl, but it's waiting on Reactive v0.3.7.

**Comment by rdeits** [comment]
I'm also happy to make the METADATA PR myself, if you'd like.

**Comment by SimonDanisch** [comment]
Fine by me. @shashi I don't see the bug anymore that I mentioned to you.

**Comment by shashi** [comment]
I was going to open this issue and ping you @SimonDanisch , I'll go ahead and tag it then!

**Comment by shashi** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/7817

**Comment by rdeits** [comment]
Awesome, thank you :)
