### ISSUE TITLE
function filter has 3 parameters but in the doc 2

### ISSUE THREAD

**Issue by giuan** [JuliaGizmos/Reactive.jl#125]
In the doc function **filter** is `filter(f,signal)` but in the code is `filter(f, default, signal)` 

What is default?

**Comment by JobJob** [comment]
It's the initial value the signal will hold if `f(value(signal))` is false when the filter is created. E.g.
```
using Reactive

s = Signal(5)
#keep s > 10, but since s is 5, it will initially have the default value 100
sgt10 = filter(x->x > 10, 100, s)

#keep s <= 10, default not used
slte10 = filter(x->x <= 10, 0, s)

value(sgt10), value(slte10)
```
```
(100, 5)
```

Thanks for reporting. This should be added to the docstring, and the docs fixed. PR welcome.

**Comment by giuan** [comment]
Thank you.

**Comment by JobJob** [comment]
Fixed on master
