### ISSUE TITLE
A map version that doesn't evaluate before the first push to its Signal

### ISSUE THREAD

**Issue by yakir12** [JuliaGizmos/Reactive.jl#130]
I find myself writing a lot of:
```julia
a = Signal(1)
b = map(a, init = nothing) do x
    <do things with x>
    return nothing
end
```
I'm sure I could resolve some of these occurrences through better programming, but it would be handy to have a version of `map` that doesn't evaluate before the first `push!` to its `Signal`, `mapinit`?

**Comment by shashi** [comment]
Hello. Sorry, I'm having some trouble understanding the question. Setting `init = nothing` should cause the function to not execute upon the creation of the signal. (as opposed to passing no `init` keyword argument.). Is that not what you're seeing?

**Comment by yakir12** [comment]
It is, it is. Sorry for not being clearer, this is more of feature request. It would be useful if there was a version of the `map` function that did that on default, so:
```julia
b = mapinit(a) do x
    <do things with x>
end
```
would be equivalent to:
```julia
b = map(a, init = nothing) do x
    <do things with x>
    return nothing
end
```

**Comment by shashi** [comment]
Ah, I see. I'm afraid that is slightly complicated, because:

1. You need to know what's the value of `T` to construct `Signal{T}` right now, we can take that to be the type of the value. This is easy to "fix" by just setting `T` to `Any` or using `Base.promote_op`.
2. If someone tries to use `b` in your example to create another signal `c` (maybe `map(f, b)`) then you need to know the value of `b` at that point to create `c`.

It seems you're specifically interested in returning `nothing` here. Perhaps `foreach` might be a better fit for your use case.

**Comment by yakir12** [comment]
I see. `foreach` would take care of the redundant return `Signal`, but I'll still need to specify an `init` to prevent the `Signal` from evaluating (which in my case is the reason I specify an `init` value and a specific return value for the function of the `Signal` -- most conveniently a `nothing`).

OK, closing this now, thanks for all the awesome work!!!

**Comment by timholy** [comment]
This is, I think, a consequence of `map` being useful for two things:

- a way of creating a new Signal out of existing ones
- a way of defining a callback that runs when a Signal updates

In the second case you don't necessarily need any output at all, and could set up the callback without creating a new Signal. In such cases it wouldn't have to run once.

**Comment by shashi** [comment]
Yes, seems like some renamed form of `foreach` e.g. `foreach_noinit(f, xs...) = foreach(f, xs...; init=nothing)` should take care of the 2nd case I think.

**Comment by timholy** [comment]
I can't resist linking to https://github.com/JuliaGizmos/Observables.jl/issues/1#issuecomment-292778303; while I'm sure the timing is suspicious, I swear I'm not paying @yakir12 to ask this question right now :smile:.

**Comment by yakir12** [comment]
It's true. Believe me. 

You'll need to somehow make sure it works regardless of what the `Signal`'s function returns (even if it's not `nothing`).
