### ISSUE TITLE
GC on preserve?

### ISSUE THREAD

**Issue by nico202** [JuliaGizmos/Reactive.jl#135]
Hi, I'm in a situation in which if I
`    preserve(map(_->my_function(), fps(10))`
with
`    my_function() = println("hi")`
I see just "hi" one-time and then nothing happens.
Why?

**Comment by timholy** [comment]
I can't reproduce this.

**Comment by nico202** [comment]
Updating Reactive from 0.3.7 to 0.4.0 and now it does work... I'll reopen this issue if this happens again, thanks
