### ISSUE TITLE
Should bind! ellicit a push!?

### ISSUE THREAD

**Issue by yakir12** [JuliaGizmos/Reactive.jl#141]
Shouty title not intended (just due to syntax).

I'm using `Reactive` (with `GtkReactive`) in a GUI. To build the GUI, I needed to `bind!` two `Signals`. But almost all the `push!` events in this GUI should only come from the user pressing on buttons etc, not from building the GUI. 

Hence, I'm wondering how wrong would it would be to bind signals without eliciting an immediate push-event to the source `Signal`? If this is a too-big change that doesn't make sense, maybe you can add an argument to bind the two signals "silently"?

**Comment by JobJob** [comment]
> Shouty title not intended (just due to syntax).

Lol

> I'm wondering how wrong would it would be to bind signals without eliciting an immediate push-event to the source Signal

1) Do you mean to the **dest** Signal?
1a) or maybe you are doing a two-way bind?

> maybe you can add an argument to bind the two signals "silently"

So basically, bind them for future updates, but initially they won't have the same value? Do you get the behaviour you want if you comment out [this line in Reactive](https://github.com/JuliaGizmos/Reactive.jl/blob/master/src/operators.jl#L362)? If so do you want to add a keyword argument to bind, e.g. `bind!(...; initial=true)` ? and then you'd set `initial = false` for your case and it we'd just change that line to `initial && bind_updater(src.value)` ?

**Comment by yakir12** [comment]
1. Sorry, yea, meant to the dest Signal.
   1a) No. 
> So basically, bind them for future updates, but initially they won't have the same value?

Exactly.
> Do you get the behaviour you want if you comment out this line in Reactive?

Yes I do.
> If so do you want to add a keyword argument to bind, e.g. bind!(...; initial=true) ? and then you'd set initial = false for your case and it we'd just change that line to initial && bind_updater(src.value) ?

Yes, that would do the trick. I should be able to do that (but realistically only tomorrow).

**Comment by JobJob** [comment]
👍

**Comment by yakir12** [comment]
done #142

**Comment by yakir12** [comment]
Any way I can help you release the next version of `Reactive`? I'm writing packages that depend on the `bind!` functionality we added here...?

**Comment by JobJob** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/9464 - thanks!
