### ISSUE TITLE
Maybe restart disrespects a stopped event loop

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaGizmos/Reactive.jl#144]
This line:
https://github.com/JuliaGizmos/Reactive.jl/blob/master/src/core.jl#L389

Will restart the event loop, even if it was manually stopped. So it basically becomes impossible to stop the event loop, since it will just restart automatically at some later point.

**Comment by JobJob** [comment]
Hi Simon, do you by chance have some simple code that triggers this? I was under the impression that this line is the guard against that situation: https://github.com/JuliaGizmos/Reactive.jl/blob/master/src/core.jl#L379
In a notebook with these 5 cells, I get the output below each block
```
using Reactive

s = Signal(1)
m = map(identity, s)
push!(s, 3)
```
```
value(m)
```
3
```
Reactive.stop()
push!(s, 2)
```
```
value(m)
```
3 (i.e. didn't get changed to 2, implying queue is stopped)
```
Base.n_avail(Reactive._messages)
```
1 (the `push!(s, 2)` is still in the queue)

**Comment by SimonDanisch** [comment]
It restarts as soon as you try to poll manually, which is what i wanted to have the stop for ;)

**Comment by JobJob** [comment]
What do you mean poll manually?

**Comment by SimonDanisch** [comment]
Running `run_till_now()`

**Comment by JobJob** [comment]
Not able to reproduce that behaviour unfort. e.g. say I add these cells after the above:
```
Reactive.run_till_now()
```
```
value(s)
```
2
```
m3 = map(x->3x, s)
```
6
```
push!(s, 4)
```
```
value(m3)
```
6
(not 8)

Do you have a minimal test case?

**Comment by SimonDanisch** [comment]
Hm I think you're right... Seems like my problem is somewhere else...

**Comment by SimonDanisch** [comment]
found the bug: https://github.com/JuliaGizmos/Reactive.jl/pull/146
