### ISSUE TITLE
Signal(null) - Question on usage

### ISSUE THREAD

**Issue by hgeorgako** [JuliaGizmos/Reactive.jl#148]
How can I get something like this to work?

```julia
using Nulls

a = Signal(null)
push!(a, 2.3)
```

**Comment by shashi** [comment]
I think the premise of Nulls.jl is that you should be able to use `Union{Null, T}` for missing values.

So, `a = Signal(Union{Null, Float64}, null)` should let you push a 2.3 onto it. Cheers!
