### ISSUE TITLE
Cleanup gc'ed WeakRef from nodes and edges

### ISSUE THREAD

**Issue by TsurHerman** [JuliaGizmos/Reactive.jl#149]
Probably a low priority issue:
It would be helpful to have a cleanup function
that would call the GC implicitly and then prune the nodes and edges.

I noticed that Reactive.nodes just grows even if the signals it weakref's has already been GC'ed
I don't now if this has any complications ..

**Comment by JobJob** [comment]
> I noticed that Reactive.nodes just grows even if the signals it weakref's has already been GC'ed

It shouldn't -  https://github.com/JuliaGizmos/Reactive.jl/blob/master/src/core.jl#L171 - can you check if that function is being run in your case - e.g. by adding a `@show nodes` at the start of that function.

**Comment by TsurHerman** [comment]
Your right, I was testing it in conjunction with glvisualize .. recreating many windows with Reactive
controls.
Due (probably) to the nested nature of he signals in glvisualize , it takes several gc() calls to collect all unused signals.

After that a push! to any signal does indeed clear the dead nodes.

**Comment by JobJob** [comment]
Ok thanks! cc @SimonDanisch just in case, though I imagine he knows what's going on.
