### ISSUE TITLE
Unexpected behavior when using push! on a foldp-Signal

### ISSUE THREAD

**Issue by Hydrolik** [JuliaGizmos/Reactive.jl#166]
When a foldp-Signal is updated after a value has been pushed to it, it will not use the pushed value, but the previous value. Example:

```julia
s = Signal(1)
fp = foldp(+, 0, s)

value(fp)       # 0
push!(fp, 100)
value(fp)       # 100
push!(s, 1)
value(fp)       # 1
```

I would expect the last value to be 101, rather than 1.

**Comment by JobJob** [comment]
That seems reasonable. 

I think it should work if you change this function https://github.com/JuliaGizmos/Reactive.jl/blob/master/src/operators.jl#L125-L132
to
```
function connect_foldp(f, v0, output, inputs)
    add_action!(output) do
        vals = map(value, inputs)
        set_value!(output, f(output.value, vals...))
    end
end
```

Do you want to try that, add a test, and make a Pull Request? That'd be good :)
