### ISSUE TITLE
Channel size

### ISSUE THREAD

**Issue by mschauer** [JuliaGizmos/Reactive.jl#169]
I have a somewhat more complicated Makie plot and run into channel size issues. I see that the channel size is hardcoded to 1024. Should it be possible to increase that?

Edit: I guess the outcommented lines strain the message queue are the loops are looping over 500 line vectors. https://github.com/mschauer/Bridge.jl/blob/partial2/example/makie.jl#L23

**Comment by JobJob** [comment]
Yeah, as far as I understand that limit is pretty arbitrary. If you want to make it modifiable I guess you'd just change this line https://github.com/JuliaGizmos/Reactive.jl/blob/master/src/core.jl#L17 to:

`const CHANNEL_SIZE = get(ENV, "REACTIVE_CHANNEL_SIZE", 1024)` 
then set `ENV["REACTIVE_CHANNEL_SIZE"] = ???` in your ~/.juliarc.jl

PR welcome.
