### ISSUE TITLE
WARNING: closing a non-leaf node is not a good idea Failed to push!

### ISSUE THREAD

**Issue by dioptre** [JuliaGizmos/Reactive.jl#87]
Hi @shashi 

Just wondering what to do to terminate a signal if not to Reactive.close it?

Thanks
A

**Comment by shashi** [comment]
Just let it go out of scope.

I think this warning is a little alarmist and shouldn't be there.

**Comment by dioptre** [comment]
OK, I want to stop animations voluntarily on a single page - so not 100%
sure how to let it go out of scope.

I think close is the best bet!?

Thanks
A

**Comment by shashi** [comment]
close will close a signal forever. if that's fine, then use it.

**Comment by dioptre** [comment]
Thanks! Sounds good - is it ok to remove the warning then?

Thanks!

**Comment by JobJob** [comment]
Warning is removed, closing this, cheers.
